### ISSUE TITLE
Crash on system with an external sound card

### ISSUE THREAD

**Issue by markusmoenig** [Rodrigodd/audio-engine#8]
I have a beta user for eldiron.com who send me this screenshot of a crash inside the audio-engine. He said he has an external sound card, he is not a developer so unable to debug this further.

![image_audio](https://user-images.githubusercontent.com/10293923/207204411-c0a3b662-4473-4882-88c8-4e12fc6ac419.png)

**Comment by markusmoenig** [comment]
If conversions are not supported, can we just continue normal operations instead of panicking ?

**Comment by Rodrigodd** [comment]
This panic happens, for example, when an Audio Source has 2 channels, but the device output has 3. When I implemented channel conversion and didn't know how to properly make an n:m conversion, so I only implemented 1:n and n:1, which were straight forward.

I still don't know how to do the conversion properly (I am afraid that it is not even possible), but I could do an n:1:m conversion instead of panicking. This may raise the issue of losing stereo audio, though.

I may be able to take a look at this tomorrow or on the weekend.

[Here is the line with the panic, for reference](https://github.com/Rodrigodd/audio-engine/blob/78e50e47ea81b0c74d92626c00b1b45b689c7ded/src/converter.rs#L187).

**Comment by markusmoenig** [comment]
Thanks a lot!

I do not mind loosing the stereo in these cases (as in my use case these are all retro sounds / audio anyway). But main thing is no crash :)

**Comment by Rodrigodd** [comment]
I have fixed this on 48953f6bfa4de0e8ac60615ac3e9de7b26eb9109. If you could test master branch, at least to make sure that I have not introduced any regression. If everything is okay, I can publish a new version.

**Comment by markusmoenig** [comment]
Great, thanks. I tested it on the Desktops and it seems to work fine (cannot test it on the Web right now as my code is broken there atm). I think it should be good to go.

**Comment by Rodrigodd** [comment]
Fixed on v0.4.5.
