### ISSUE TITLE
Send + Sync traits

### ISSUE THREAD

**Issue by markusmoenig** [Rodrigodd/audio-engine#9]
Hi,

I am changing my app layout a bit and now require Send and Sync in my classes. Audio Engine fails with

`Sender<audio_engine::engine::backend::StreamEvent>` cannot be shared between threads safely
within `ScreenEditor<'_>`, the trait `Sync` is not implemented for `Sender<audio_engine::engine::backend::StreamEvent>`

I guess there are more traits which fail. Is it possible to add Send + Sync support ? Rhai for example has implemented this using a "Sync" feature.

Thanks

**Comment by Rodrigodd** [comment]
Currently, `AudioEngine` is only `Send` on non-wasm platform. On a non-wasm platform, the `cpal::Stream` (which is `!Send`) is created in another thread, so `AudioEngine` don't need to contain it. But on wasm there are no threads, so `AudioEngine` becomes `!Send` because it needs to hold a `cpal::WebAudioStream`. I tried patching `cpal` to make `WebAudioStream` `Send`, but it didn't work out.

But I could make `AudioEngine` be `Sync` in both scenarios fairly easy, by wrapping `Backend` in [something like this](https://github.com/Nemo157/async-compression/blob/c75e6c5/src/unshared.rs#L5-L33). Would this change be enough, or at least help?

**Comment by markusmoenig** [comment]
Yes it would help!

I think Sync is the main missing part here, not Send. 

Thanks!

**Comment by Rodrigodd** [comment]
@markusmoenig Implemented that on 3d2b6c0c48453af09d3417833a853580785ff3bc. See if it is good for you.

**Comment by markusmoenig** [comment]
Yes, perfect, thanks a lot!
